---
# base packages role should tell us smowthing about our system
print_os_vars: true

# user auth ssh keys
users:
  l3d:
    - l3d@derpy.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@pinkie.l3d.yt
    - l3d@business.wingcon.com
    - l3d@backup-rsa.l3d.yt
    - l3d@backup.l3d.yt

github_users:
  l3d:
    - do1jlr
# admins with root permission
admins:
  - l3d

# users that should be created
accounts:
  - l3d

# personal configuration for weechat.
# For explaination please have a look into ``roles/weechat/README.md``
weechat:
  user: 'l3d'
  autostart: true
  install_plugins: true
  use_custom_config: true
  home_directory: "/home/l3d"
  custom_config:
    private_repo: gitea@gitea.see-base.de:l3d/weechat-config.git

# create ssh directory
ssh_public_key_store: 'admin_ssh_keys'

# we want a simple versionscheck on all our submodules
# -> to make sure we never use a old version of a role
submodules_versioncheck: true
