---
- name: Install common packages
  hosts: all
  tags:
    - base
    - packages
    - setup
    - base_packages
    - base-packages
    - update
    - upgrade
  roles:
    - base_packages
  vars:
    ansible_ssh_user: root

- name: Setup SSH and manage user
  hosts: all
  tags:
    - ssh
    - sshd
    - ssh-auth
    - ssh_auth
    - ssh-keys
    - update
    - users
    - user
    - default
  roles:
    - ssh-auth
    - sshd
  vars:
    ansible_ssh_user: root

- name: Create good dotfiles
  hosts: all
  tags:
    - dotfiles
    - bashrc
    - vimrc
    - home
    - fancy
  roles:
   - dotfiles

- name: install and configure weechat
  hosts: all
  tags:
    - defualt
    - weechat
    - install
    - conf
    - configure
  roles:
   - weechat
