---
- name: check if ansible is not to old
  hosts: localhost
  tags:
   - default
  roles:
    - version
  gather_facts: no

- name: Install common packages
  hosts: all
  tags:
    - base
    - packages
    - setup
    - base_packages
    - base-packages
    - update
    - upgrade
  roles:
    - base_packages

- name: Setup SSH, SSHD and manage users
  hosts: all
  tags:
    - ssh
    - sshd
    - ssh-auth
    - ssh_auth
    - ssh-keys
    - update
    - users
    - user
    - default
  roles:
    - manage-users
    - ssh-auth
    - sshd

- name: Create good dotfiles
  hosts: all
  tags:
    - dotfiles
    - bashrc
    - vimrc
    - home
    - fancy
    - bat
    - ntp
  roles:
   - dotfiles
   - bat
   - ntp

- name: install and configure weechat
  hosts: all
  tags:
    - defualt
    - weechat
    - install
    - conf
    - configure
  roles:
   - weechat
   - weechat-matrix-setup
