---
- name: install requirements for matrix
  become: true
  package:
    name:
      - python3-dev
      - python3-pip
      - libxml2-dev
      - libxslt-dev
      - gcc
      - g++
      - python3-setuptools
      - python3-distutils-extra
      - python3-pytest
      - python3-future
      - python3-cffi

